# Generated by Django 6.1.1 on 2026-09-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
