# Generated by Django 6.1.1 on 2026-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='date_from',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='date_to',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
