# Generated by Django 6.1.1 on 2026-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='fold_groups',
            field=models.BooleanField(default=True),
        ),
    ]
