# Generated by Django 6.1.1 on 2026-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savedsearch_fold_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='group_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
