# Generated by Django 6.1.1 on 2026-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_savedsearch_group_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('home', 'Home'), ('subscriptions', 'Subscriptions'), ('bills', 'Bills'), ('health', 'Health'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('education', 'Education'), ('gift', 'Gift'), ('cash', 'Cash'), ('pet', 'Pet'), ('tag', 'Other')], default='tag', max_length=20),
        ),
    ]
